<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
* { margin:0; padding:0; box-sizing:border-box; }
body { font-family:'DejaVu Sans',sans-serif; font-size:8.5pt; color:#111; }

.header { text-align:center; padding-bottom:10px; border-bottom:3px solid #0D2144; margin-bottom:12px; position:relative; }
.header .logo-left  { position:absolute; left:0; top:0; width:55px; height:55px; }
.header .logo-right { position:absolute; right:0; top:0; width:55px; height:55px; }
.header .titles { padding:0 70px; }
.brgy { font-size:14pt; font-weight:bold; text-transform:uppercase; color:#0D2144; letter-spacing:0.05em; }
.report-title { text-align:center; font-size:13pt; font-weight:bold; text-transform:uppercase; letter-spacing:0.08em; color:#0D2144; margin:10px 0 2px; text-decoration:underline; }
.report-sub   { text-align:center; font-size:8pt; color:#666; margin-bottom:10px; }
.meta-bar { background:#f0f4f8; border:1px solid #dde2ea; border-radius:4px; padding:5px 10px; margin-bottom:12px; display:flex; justify-content:space-between; font-size:7.5pt; color:#444; }

.section { margin-bottom:14px; }
.section-title { background:#0D2144; color:#fff; padding:5px 10px; font-size:8pt; font-weight:bold; text-transform:uppercase; letter-spacing:0.06em; }

.stat-grid { display:flex; border:1px solid #dde2ea; border-top:none; margin-bottom:12px; }
.stat-box { flex:1; text-align:center; padding:10px 6px; border-right:1px solid #dde2ea; }
.stat-box:last-child { border-right:none; }
.stat-num   { font-size:16pt; font-weight:bold; color:#0D2144; }
.stat-label { font-size:7pt; color:#666; margin-top:2px; text-transform:uppercase; }

table { width:100%; border-collapse:collapse; font-size:7.5pt; margin-bottom:12px; }
thead th { background:#0D2144; color:#fff; padding:5px 7px; text-align:left; font-size:7pt; text-transform:uppercase; }
tbody tr:nth-child(even) { background:#f5f7fa; }
tbody td { padding:4px 7px; border-bottom:1px solid #e5e7eb; }

.two-col { display:flex; gap:12px; margin-bottom:12px; }
.two-col .col { flex:1; }

.prog-wrap { background:#e5e7eb; border-radius:99px; height:6px; margin-top:2px; }
.prog-bar  { height:100%; border-radius:99px; background:#0D2144; }

.badge { display:inline-block; padding:1px 5px; border-radius:99px; font-size:6pt; font-weight:bold; }
.badge-green  { background:#dcfce7; color:#166534; }
.badge-red    { background:#fee2e2; color:#991b1b; }
.badge-yellow { background:#fef9c3; color:#854d0e; }
.badge-gray   { background:#f3f4f6; color:#6b7280; }
.badge-blue   { background:#dbeafe; color:#1e40af; }

.footer { margin-top:16px; padding-top:8px; border-top:2px solid #0D2144; display:flex; justify-content:space-between; align-items:flex-end; font-size:7pt; color:#555; }
.sig-line { text-align:center; min-width:160px; }
.sig-line .line { border-top:1px solid #333; margin-bottom:3px; }
.sig-name  { font-weight:bold; font-size:7.5pt; text-transform:uppercase; }
.sig-title { font-size:7pt; color:#666; }
</style>
</head>
<body>


<div class="header">
    <img class="logo-left"  src="<?php echo e(public_path('images/qc-seal.png')); ?>" alt="QC">
    <img class="logo-right" src="<?php echo e(public_path('images/bne-logo.png')); ?>" alt="BNE">
    <div class="titles">
        <div style="font-size:8pt;font-style:italic;color:#444"><em>Republic of the Philippines</em></div>
        <div style="font-size:8pt;color:#555">City of Quezon, National Capital Region</div>
        <div class="brgy">Barangay New Era</div>
        <div style="font-size:8pt;color:#555;font-style:italic">Office of the Punong Barangay</div>
    </div>
</div>

<div class="report-title">
    <?php echo e(strtoupper($type)); ?> <?php echo e(strtoupper(str_replace('_',' ',$module))); ?> REPORT
</div>
<div class="report-sub"><?php echo e($periodLabel); ?> &nbsp;·&nbsp; <?php echo e($startDate->format('m/d/Y')); ?> to <?php echo e($endDate->format('m/d/Y')); ?></div>

<div class="meta-bar">
    <span>Generated by: <strong><?php echo e($generatedBy); ?></strong></span>
    <span><?php echo e($generatedAt); ?></span>
</div>


<?php if($module === 'summary'): ?>

<div class="section">
    <div class="section-title">Population Overview</div>
    <div class="stat-grid">
        <div class="stat-box"><div class="stat-num"><?php echo e(number_format($data['total_residents'])); ?></div><div class="stat-label">Total Residents</div></div>
        <div class="stat-box"><div class="stat-num" style="color:#16a34a"><?php echo e(number_format($data['new_residents'])); ?></div><div class="stat-label">New This Period</div></div>
        <div class="stat-box"><div class="stat-num"><?php echo e(number_format($data['total_households'])); ?></div><div class="stat-label">Households</div></div>
        <div class="stat-box"><div class="stat-num" style="color:#16a34a"><?php echo e(number_format($data['new_households'])); ?></div><div class="stat-label">New Households</div></div>
    </div>
</div>

<div class="two-col">
    <div class="col">
        <div class="section-title">Documents</div>
        <table>
            <thead><tr><th>Metric</th><th>Count</th></tr></thead>
            <tbody>
                <tr><td>Issued This Period</td><td><strong><?php echo e(number_format($data['documents_issued'])); ?></strong></td></tr>
                <tr><td>Released</td><td><strong><?php echo e(number_format($data['documents_released'])); ?></strong></td></tr>
            </tbody>
        </table>
        <?php if($data['docs_by_type']->count()): ?>
        <table>
            <thead><tr><th>Document Type</th><th>Count</th></tr></thead>
            <tbody>
                <?php $__currentLoopData = $data['docs_by_type']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $type => $count): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                <tr><td><?php echo e($type); ?></td><td><?php echo e($count); ?></td></tr>
                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
            </tbody>
        </table>
        <?php endif; ?>
    </div>
    <div class="col">
        <div class="section-title">Blotter Cases</div>
        <table>
            <thead><tr><th>Metric</th><th>Count</th></tr></thead>
            <tbody>
                <tr><td>Filed This Period</td><td><strong><?php echo e(number_format($data['blotter_filed'])); ?></strong></td></tr>
                <tr><td>Settled</td><td><strong><?php echo e(number_format($data['blotter_settled'])); ?></strong></td></tr>
            </tbody>
        </table>
        <?php if($data['blotter_by_type']->count()): ?>
        <table>
            <thead><tr><th>Incident Type</th><th>Count</th></tr></thead>
            <tbody>
                <?php $__currentLoopData = $data['blotter_by_type']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $type => $count): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                <tr><td><?php echo e($type); ?></td><td><?php echo e($count); ?></td></tr>
                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
            </tbody>
        </table>
        <?php endif; ?>
    </div>
</div>

<div class="section">
    <div class="section-title">Demographics & Classifications</div>
    <table>
        <thead><tr><th>Classification</th><th>Count</th><th>%</th></tr></thead>
        <tbody>
            <?php
                $demos = [
                    ['Male',              $data['total_male']],
                    ['Female',            $data['total_female']],
                    ['Registered Voters', $data['voters']],
                    ['Senior Citizens',   $data['seniors']],
                    ['PWD',               $data['pwd']],
                ];
                $total = $data['total_residents'];
            ?>
            <?php $__currentLoopData = $demos; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $d): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
            <tr>
                <td><?php echo e($d[0]); ?></td>
                <td><strong><?php echo e(number_format($d[1])); ?></strong></td>
                <td><?php echo e($total > 0 ? round(($d[1]/$total)*100) : 0); ?>%</td>
            </tr>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
        </tbody>
    </table>
</div>

<div class="section">
    <div class="section-title">Business Permits</div>
    <div class="stat-grid">
        <div class="stat-box"><div class="stat-num"><?php echo e(number_format($data['businesses_active'])); ?></div><div class="stat-label">Active Businesses</div></div>
        <div class="stat-box"><div class="stat-num" style="color:#16a34a"><?php echo e(number_format($data['businesses_new'])); ?></div><div class="stat-label">New This Period</div></div>
    </div>
</div>


<?php elseif($module === 'residents'): ?>
<div class="section">
    <div class="section-title">Residents Registered This Period</div>
    <div class="stat-grid">
        <div class="stat-box"><div class="stat-num"><?php echo e(number_format($data['total'])); ?></div><div class="stat-label">Total</div></div>
        <div class="stat-box"><div class="stat-num" style="color:var(--navy)"><?php echo e(number_format($data['male'])); ?></div><div class="stat-label">Male</div></div>
        <div class="stat-box"><div class="stat-num" style="color:#C8861A"><?php echo e(number_format($data['female'])); ?></div><div class="stat-label">Female</div></div>
    </div>
</div>
<?php if($data['records']->count()): ?>
<table>
    <thead><tr><th>#</th><th>Name</th><th>Gender</th><th>Age</th><th>Purok</th><th>Address</th><th>Status</th><th>Date</th></tr></thead>
    <tbody>
        <?php $__currentLoopData = $data['records']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $i => $r): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
        <tr>
            <td style="color:#888"><?php echo e($i+1); ?></td>
            <td><strong><?php echo e($r->last_name); ?>, <?php echo e($r->first_name); ?></strong></td>
            <td><?php echo e($r->gender); ?></td>
            <td><?php echo e($r->age ?? '—'); ?></td>
            <td><?php echo e($r->purok->name ?? '—'); ?></td>
            <td><?php echo e($r->address); ?></td>
            <td><span class="badge <?php echo e($r->residency_status === 'Active' ? 'badge-green' : 'badge-gray'); ?>"><?php echo e($r->residency_status); ?></span></td>
            <td><?php echo e($r->created_at->format('M d')); ?></td>
        </tr>
        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
    </tbody>
</table>
<?php else: ?>
<p style="text-align:center;color:#666;padding:20px">No residents registered in this period.</p>
<?php endif; ?>


<?php elseif($module === 'documents'): ?>
<div class="section">
    <div class="section-title">Documents Summary</div>
    <div class="stat-grid">
        <div class="stat-box"><div class="stat-num"><?php echo e(number_format($data['total'])); ?></div><div class="stat-label">Total Issued</div></div>
        <div class="stat-box"><div class="stat-num" style="color:#16a34a"><?php echo e(number_format($data['released'])); ?></div><div class="stat-label">Released</div></div>
        <div class="stat-box"><div class="stat-num" style="color:#C8861A"><?php echo e(number_format($data['pending'])); ?></div><div class="stat-label">Pending</div></div>
    </div>
</div>
<?php if($data['by_type']->count()): ?>
<div class="section">
    <div class="section-title">By Document Type</div>
    <table><thead><tr><th>Type</th><th>Count</th></tr></thead>
    <tbody><?php $__currentLoopData = $data['by_type']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $t => $c): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr><td><?php echo e($t); ?></td><td><strong><?php echo e($c); ?></strong></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tbody>
    </table>
</div>
<?php endif; ?>
<?php if($data['records']->count()): ?>
<table>
    <thead><tr><th>#</th><th>Doc No.</th><th>Type</th><th>Resident</th><th>Status</th><th>Date</th></tr></thead>
    <tbody>
        <?php $__currentLoopData = $data['records']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $i => $d): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
        <tr>
            <td style="color:#888"><?php echo e($i+1); ?></td>
            <td style="font-family:monospace;font-size:7pt"><?php echo e($d->doc_number); ?></td>
            <td><?php echo e($d->document_type); ?></td>
            <td><?php echo e($d->resident->full_name ?? '—'); ?></td>
            <td><span class="badge <?php echo e($d->status === 'Released' ? 'badge-green' : ($d->status === 'Pending' ? 'badge-yellow' : 'badge-blue')); ?>"><?php echo e($d->status); ?></span></td>
            <td><?php echo e($d->created_at->format('m/d/Y')); ?></td>
        </tr>
        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
    </tbody>
</table>
<?php endif; ?>


<?php elseif($module === 'blotter'): ?>
<div class="section">
    <div class="section-title">Blotter Summary</div>
    <div class="stat-grid">
        <div class="stat-box"><div class="stat-num"><?php echo e(number_format($data['total'])); ?></div><div class="stat-label">Total Filed</div></div>
        <div class="stat-box"><div class="stat-num" style="color:var(--crimson)"><?php echo e(number_format($data['active'])); ?></div><div class="stat-label">Active</div></div>
        <div class="stat-box"><div class="stat-num" style="color:#16a34a"><?php echo e(number_format($data['settled'])); ?></div><div class="stat-label">Settled/Closed</div></div>
    </div>
</div>
<?php if($data['by_type']->count()): ?>
<div class="section">
    <div class="section-title">By Incident Type</div>
    <table><thead><tr><th>Type</th><th>Count</th></tr></thead>
    <tbody><?php $__currentLoopData = $data['by_type']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $t => $c): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr><td><?php echo e($t); ?></td><td><strong><?php echo e($c); ?></strong></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tbody>
    </table>
</div>
<?php endif; ?>
<?php if($data['records']->count()): ?>
<table>
    <thead><tr><th>#</th><th>Case No.</th><th>Type</th><th>Complainant</th><th>Respondent</th><th>Responding Officer</th><th>Status</th><th>Date</th></tr></thead>
    <tbody>
        <?php $__currentLoopData = $data['records']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $i => $b): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
        <tr>
            <td style="color:#888"><?php echo e($i+1); ?></td>
            <td style="font-family:monospace;font-size:7pt"><?php echo e($b->case_number); ?></td>
            <td><?php echo e($b->incident_type); ?></td>
            <td><?php echo e($b->complainant_name ?? '—'); ?></td>
            <td><?php echo e($b->respondent_name ?? '—'); ?></td>
            <td><?php echo e($b->responding_officer ?? '—'); ?></td>
            <td><span class="badge <?php echo e($b->status === 'Settled' ? 'badge-green' : ($b->status === 'Active' ? 'badge-red' : 'badge-gray')); ?>"><?php echo e($b->status); ?></span></td>
            <td><?php echo e($b->created_at->format('m/d/Y')); ?></td>
        </tr>
        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
    </tbody>
</table>
<?php endif; ?>


<?php elseif($module === 'businesses'): ?>
<div class="section">
    <div class="section-title">Business Permits Summary</div>
    <div class="stat-grid">
        <div class="stat-box"><div class="stat-num"><?php echo e(number_format($data['total'])); ?></div><div class="stat-label">Total</div></div>
        <div class="stat-box"><div class="stat-num" style="color:#16a34a"><?php echo e(number_format($data['active'])); ?></div><div class="stat-label">Active</div></div>
        <div class="stat-box"><div class="stat-num" style="color:var(--crimson)"><?php echo e(number_format($data['expired'])); ?></div><div class="stat-label">Expired</div></div>
    </div>
</div>
<?php if($data['records']->count()): ?>
<table>
    <thead><tr><th>#</th><th>Permit No.</th><th>Business</th><th>Type</th><th>Owner</th><th>Status</th></tr></thead>
    <tbody>
        <?php $__currentLoopData = $data['records']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $i => $b): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
        <tr>
            <td style="color:#888"><?php echo e($i+1); ?></td>
            <td style="font-family:monospace;font-size:7pt"><?php echo e($b->permit_number); ?></td>
            <td><strong><?php echo e($b->business_name); ?></strong></td>
            <td><?php echo e($b->business_type); ?></td>
            <td><?php echo e($b->owner_name); ?></td>
            <td><span class="badge <?php echo e($b->status === 'Active' ? 'badge-green' : ($b->status === 'Expired' ? 'badge-red' : 'badge-yellow')); ?>"><?php echo e($b->status); ?></span></td>
        </tr>
        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
    </tbody>
</table>
<?php endif; ?>
<?php endif; ?>


<div class="footer">
    <div style="font-size:7pt;color:#888"><em>This document is for official use only.</em><br>Barangay New Era Management System</div>
    <div style="display:flex;gap:40px;align-items:flex-end">
        <div class="sig-line">
            <div style="height:28px"></div>
            <div class="line"></div>
            <div class="sig-name"><?php echo e($secretaryName); ?></div>
            <div class="sig-title">Barangay Secretary</div>
        </div>
        <div class="sig-line">
            <div style="height:28px"></div>
            <div class="line"></div>
            <div class="sig-name"><?php echo e($officialName); ?></div>
            <div class="sig-title">Punong Barangay</div>
        </div>
    </div>
</div>

</body>
</html><?php /**PATH D:\laragon\www\anakco_bms\resources\views/reports/pdf.blade.php ENDPATH**/ ?>