<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
* { margin:0; padding:0; box-sizing:border-box; }
body { font-family: 'DejaVu Sans', sans-serif; font-size: 8.5pt; color: #111; }
.header { text-align:center; padding-bottom:10px; border-bottom:3px solid #0D2144; margin-bottom:14px; position:relative; }
.header .logo-left  { position:absolute; left:0; top:0; width:55px; height:55px; }
.header .logo-right { position:absolute; right:0; top:0; width:55px; height:55px; }
.header .titles { padding:0 70px; }
.brgy { font-size:14pt; font-weight:bold; text-transform:uppercase; color:#0D2144; letter-spacing:0.05em; }
.sub  { font-size:8pt; color:#555; font-style:italic; }
.addr { font-size:7.5pt; color:#777; }
.report-title { text-align:center; font-size:13pt; font-weight:bold; text-transform:uppercase; letter-spacing:0.1em; color:#0D2144; margin:10px 0 2px; text-decoration:underline; }
.report-sub   { text-align:center; font-size:7.5pt; color:#666; margin-bottom:12px; }
.meta-bar { background:#f0f4f8; border:1px solid #dde2ea; border-radius:4px; padding:5px 10px; margin-bottom:14px; display:flex; justify-content:space-between; font-size:7.5pt; color:#444; }

/* Section */
.section { margin-bottom:14px; }
.section-title { background:#0D2144; color:#fff; padding:5px 10px; font-size:8pt; font-weight:bold; text-transform:uppercase; letter-spacing:0.06em; margin-bottom:0; }

/* Stat grid */
.stat-grid { display:flex; border:1px solid #dde2ea; border-top:none; }
.stat-box { flex:1; text-align:center; padding:10px 6px; border-right:1px solid #dde2ea; }
.stat-box:last-child { border-right:none; }
.stat-num   { font-size:16pt; font-weight:bold; color:#0D2144; line-height:1; }
.stat-label { font-size:7pt; color:#666; margin-top:3px; text-transform:uppercase; letter-spacing:0.04em; }

/* Table */
table { width:100%; border-collapse:collapse; font-size:8pt; }
thead th { background:#0D2144; color:#fff; padding:5px 8px; text-align:left; font-size:7.5pt; text-transform:uppercase; }
tbody tr:nth-child(even) { background:#f5f7fa; }
tbody td { padding:5px 8px; border-bottom:1px solid #e5e7eb; }

/* Two col layout */
.two-col { display:flex; gap:12px; margin-bottom:14px; }
.two-col .col { flex:1; }

/* Progress bar */
.prog-wrap { background:#e5e7eb; border-radius:99px; height:7px; margin-top:3px; overflow:hidden; }
.prog-bar  { height:100%; border-radius:99px; }

/* Footer */
.footer { margin-top:16px; padding-top:8px; border-top:2px solid #0D2144; display:flex; justify-content:space-between; align-items:flex-end; font-size:7pt; color:#555; }
.sig-line { text-align:center; min-width:160px; }
.sig-line .line { border-top:1px solid #333; margin-bottom:3px; }
.sig-name  { font-weight:bold; font-size:7.5pt; text-transform:uppercase; }
.sig-title { font-size:7pt; color:#666; }
</style>
</head>
<body>

{{-- Header --}}
<div class="header">
    <img class="logo-left"  src="{{ public_path('images/qc-seal.png') }}" alt="QC">
    <img class="logo-right" src="{{ public_path('images/bne-logo.png') }}" alt="BNE">
    <div class="titles">
        <div style="font-size:8pt;font-style:italic;color:#444"><em>Republic of the Philippines</em></div>
        <div style="font-size:8pt;color:#555">City of Quezon, National Capital Region</div>
        <div class="brgy">Barangay New Era</div>
        <div class="sub">Office of the Punong Barangay</div>
        <div class="addr">New Era, Quezon City, Metro Manila</div>
    </div>
</div>

<div class="report-title">Population Summary Report</div>
<div class="report-sub">As of {{ now()->format('m/d/Y') }}</div>

<div class="meta-bar">
    <span>Generated by: <strong>{{ $generatedBy }}</strong></span>
    <span>{{ $generatedAt }}</span>
</div>

{{-- Overall Population Stats --}}
<div class="section">
    <div class="section-title">Overall Population</div>
    <div class="stat-grid">
        <div class="stat-box">
            <div class="stat-num">{{ number_format($totalResidents) }}</div>
            <div class="stat-label">Total Residents</div>
        </div>
        <div class="stat-box">
            <div class="stat-num" style="color:#16a34a">{{ number_format($totalActive) }}</div>
            <div class="stat-label">Active</div>
        </div>
        <div class="stat-box">
            <div class="stat-num" style="color:#6b7280">{{ number_format($totalDeceased) }}</div>
            <div class="stat-label">Deceased</div>
        </div>
        <div class="stat-box">
            <div class="stat-num" style="color:#C8861A">{{ number_format($totalTransferred) }}</div>
            <div class="stat-label">Transferred</div>
        </div>
        <div class="stat-box">
            <div class="stat-num">{{ number_format($totalHouseholds) }}</div>
            <div class="stat-label">Households</div>
        </div>
    </div>
</div>

{{-- Gender & Age --}}
<div class="two-col">
    {{-- Gender --}}
    <div class="col">
        <div class="section-title">Gender Distribution</div>
        <table>
            <thead><tr><th>Gender</th><th>Count</th><th>Percentage</th></tr></thead>
            <tbody>
                @php $total = $totalMale + $totalFemale; @endphp
                <tr>
                    <td>Male</td>
                    <td><strong>{{ number_format($totalMale) }}</strong></td>
                    <td>{{ $total > 0 ? round(($totalMale/$total)*100) : 0 }}%</td>
                </tr>
                <tr>
                    <td>Female</td>
                    <td><strong>{{ number_format($totalFemale) }}</strong></td>
                    <td>{{ $total > 0 ? round(($totalFemale/$total)*100) : 0 }}%</td>
                </tr>
                <tr style="background:#f0f4f8">
                    <td><strong>Total</strong></td>
                    <td><strong>{{ number_format($total) }}</strong></td>
                    <td><strong>100%</strong></td>
                </tr>
            </tbody>
        </table>
    </div>

    {{-- Age Groups --}}
    <div class="col">
        <div class="section-title">Age Groups</div>
        <table>
            <thead><tr><th>Age Group</th><th>Count</th><th>%</th></tr></thead>
            <tbody>
                @foreach($ageGroups as $label => $count)
                @php $pct = $totalActive > 0 ? round(($count/$totalActive)*100) : 0; @endphp
                <tr>
                    <td>{{ $label }}</td>
                    <td><strong>{{ number_format($count) }}</strong></td>
                    <td>{{ $pct }}%</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

{{-- Special Classifications --}}
<div class="section">
    <div class="section-title">Special Classifications</div>
    <table>
        <thead>
            <tr><th>Classification</th><th>Count</th><th>% of Active</th><th>Visual</th></tr>
        </thead>
        <tbody>
            @php
                $classifications = [
                    ['label' => 'Registered Voters', 'value' => $totalVoters,     'color' => '#0D2144'],
                    ['label' => 'Senior Citizens',   'value' => $totalSeniors,    'color' => '#C8861A'],
                    ['label' => 'PWD',               'value' => $totalPwd,        'color' => '#2563eb'],
                    ['label' => 'Solo Parents',      'value' => $totalSoloParent, 'color' => '#7c3aed'],
                    ['label' => '4Ps Beneficiaries', 'value' => $total4ps,        'color' => '#dc2626'],
                ];
            @endphp
            @foreach($classifications as $c)
            @php $pct = $totalActive > 0 ? round(($c['value']/$totalActive)*100) : 0; @endphp
            <tr>
                <td>{{ $c['label'] }}</td>
                <td><strong>{{ number_format($c['value']) }}</strong></td>
                <td>{{ $pct }}%</td>
                <td style="width:120px">
                    <div class="prog-wrap">
                        <div class="prog-bar" style="width:{{ $pct }}%;background:{{ $c['color'] }}"></div>
                    </div>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>

{{-- Residents by Purok --}}
<div class="section">
    <div class="section-title">Residents by Purok</div>
    <table>
        <thead>
            <tr><th>Purok</th><th>Residents</th><th>% of Total</th><th>Visual</th></tr>
        </thead>
        <tbody>
            @foreach($residentsByPurok as $purok)
            @php $pct = $totalActive > 0 ? round(($purok->residents_count/$totalActive)*100) : 0; @endphp
            <tr>
                <td>{{ $purok->name }}</td>
                <td><strong>{{ number_format($purok->residents_count) }}</strong></td>
                <td>{{ $pct }}%</td>
                <td style="width:120px">
                    <div class="prog-wrap">
                        <div class="prog-bar" style="width:{{ $pct }}%;background:#0D2144"></div>
                    </div>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>

{{-- Footer --}}
<div class="footer">
    <div style="font-size:7pt;color:#888">
        <em>This document is confidential. For official use only.</em><br>
        Barangay New Era Management System
    </div>
    <div style="display:flex;gap:40px;align-items:flex-end">
        <div class="sig-line">
            <div style="height:28px"></div>
            <div class="line"></div>
            <div class="sig-name">{{ $secretaryName }}</div>
            <div class="sig-title">Barangay Secretary</div>
        </div>
        <div class="sig-line">
            <div style="height:28px"></div>
            <div class="line"></div>
            <div class="sig-name">{{ $officialName }}</div>
            <div class="sig-title">Punong Barangay</div>
        </div>
    </div>
</div>

</body>
</html>