<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
* { margin:0; padding:0; box-sizing:border-box; }
body { font-family: 'DejaVu Sans', sans-serif; font-size: 8pt; color: #111; }
.header { text-align:center; padding-bottom:10px; border-bottom:3px solid #0D2144; margin-bottom:12px; position:relative; }
.header .logo-left { position:absolute; left:0; top:0; width:55px; height:55px; }
.header .logo-right { position:absolute; right:0; top:0; width:55px; height:55px; }
.header .titles { padding:0 70px; }
.header .republic { font-size:8pt; font-style:italic; color:#444; }
.header .brgy { font-size:14pt; font-weight:bold; text-transform:uppercase; color:#0D2144; letter-spacing:0.05em; }
.header .office { font-size:8pt; color:#555; font-style:italic; }
.header .address { font-size:7.5pt; color:#777; }
.report-title { text-align:center; font-size:12pt; font-weight:bold; text-transform:uppercase; letter-spacing:0.1em; color:#0D2144; margin:10px 0 3px; text-decoration:underline; }
.report-sub { text-align:center; font-size:7.5pt; color:#666; margin-bottom:10px; }
.meta-bar { background:#f0f4f8; border:1px solid #dde2ea; border-radius:4px; padding:5px 10px; margin-bottom:10px; display:flex; justify-content:space-between; font-size:7.5pt; color:#444; }
table { width:100%; border-collapse:collapse; font-size:7.5pt; }
thead { display:table-header-group; }
thead tr th { background:#0D2144; color:#fff; padding:6px 8px; text-align:left; font-size:7pt; text-transform:uppercase; letter-spacing:0.06em; border:1px solid #0a1a36; }
tbody tr { page-break-inside:avoid; }
tbody tr:nth-child(odd) { background:#fff; }
tbody tr:nth-child(even) { background:#f5f7fa; }
tbody td { padding:5px 8px; border-bottom:1px solid #e5e7eb; border-right:1px solid #f0f0f0; vertical-align:middle; }
tbody td:last-child { border-right:none; }
.badge { display:inline-block; padding:1px 5px; border-radius:99px; font-size:6.5pt; font-weight:bold; margin:1px; }
.badge-green  { background:#dcfce7; color:#166534; }
.badge-red    { background:#fee2e2; color:#991b1b; }
.badge-yellow { background:#fef9c3; color:#854d0e; }
.badge-gray   { background:#f3f4f6; color:#6b7280; }
.badge-blue   { background:#dbeafe; color:#1e40af; }
.badge-orange { background:#ffedd5; color:#9a3412; }
.badge-gold   { background:#fef3dc; color:#92600a; }
.footer { margin-top:14px; padding-top:8px; border-top:2px solid #0D2144; display:flex; justify-content:space-between; align-items:center; font-size:7pt; color:#555; }
.sig-line { text-align:center; min-width:160px; }
.sig-line .line { border-top:1px solid #333; margin-bottom:3px; width:100%; }
.sig-line .name { font-weight:bold; font-size:7.5pt; text-transform:uppercase; }
.sig-line .title { font-size:7pt; color:#666; }
</style>
</head>
<body>
<div class="header">
    <img class="logo-left"  src="{{ public_path('images/qc-seal.png') }}" alt="QC">
    <img class="logo-right" src="{{ public_path('images/bne-logo.png') }}" alt="BNE">
    <div class="titles">
        <div class="republic"><em>Republic of the Philippines</em></div>
        <div style="font-size:8pt;color:#555">City of Quezon, National Capital Region</div>
        <div class="brgy">Barangay New Era</div>
        <div class="office">Office of the Punong Barangay</div>
        <div class="address">New Era, Quezon City, Metro Manila</div>
    </div>
</div>
<div class="report-title">Blotter Cases Report</div>
<div class="report-sub">
    As of {{ now()->format('F d, Y') }}
    @if(!empty($filters['status'])) &nbsp;·&nbsp; Status: <strong>{{ $filters['status'] }}</strong> @endif
    @if(!empty($filters['incident_type'])) &nbsp;·&nbsp; Type: <strong>{{ $filters['incident_type'] }}</strong> @endif
    @if(!empty($filters['date_from'])) &nbsp;·&nbsp; From: <strong>{{ $filters['date_from'] }}</strong> @endif
    @if(!empty($filters['date_to'])) &nbsp;·&nbsp; To: <strong>{{ $filters['date_to'] }}</strong> @endif
    @if(!empty($filters['source'])) &nbsp;·&nbsp; Source: <strong>{{ ucfirst($filters['source']) }}</strong> @endif
</div>
@if(isset($activeFilters) && $activeFilters !== 'None (all records)')
<div style="background:#fef9c3;border:1px solid #fde68a;border-radius:3px;padding:4px 10px;margin-bottom:8px;font-size:7pt;color:#92400e;text-align:center">
    <strong>Filtered Export:</strong> {{ $activeFilters }}
</div>
@endif
<div class="meta-bar">
    <span>Total Records: <strong>{{ $data->count() }}</strong></span>
    <span>Generated by: <strong>{{ $generatedBy }}</strong> &nbsp;|&nbsp; {{ $generatedAt }}</span>
</div>
<table>
    <thead>
        <tr>
            <th style="width:25px">#</th>
            <th>Case No.</th>
            <th>Incident Type</th>
            <th>Date</th>
            <th>Location</th>
            <th>Complainant</th>
            <th>Respondent</th>
            <th>Status</th>
            <th>Filed By</th>
            <th>Date Filed</th>
        </tr>
    </thead>
    <tbody>
        @foreach($data as $i => $b)
        @php $cls = match($b->status) { 'Active'=>'badge-red','Settled'=>'badge-green','Closed'=>'badge-gray','Under Investigation'=>'badge-yellow',default=>'badge-orange' }; @endphp
        <tr>
            <td style="text-align:center;color:#888">{{ $i+1 }}</td>
            <td><strong>{{ $b->case_number }}</strong></td>
            <td>{{ $b->incident_type }}</td>
            <td>{{ $b->incident_date ? \Carbon\Carbon::parse($b->incident_date)->format('m/d/Y') : '—' }}</td>
            <td>{{ $b->incident_location ?? '—' }}</td>
            <td>{{ $b->complainant_name ?? '—' }}</td>
            <td>{{ $b->respondent_name ?? '—' }}</td>
            <td><span class="badge {{ $cls }}">{{ $b->status }}</span></td>
            <td>{{ $b->filedBy->name ?? '—' }}</td>
            <td>{{ $b->created_at->format('m/d/Y') }}</td>
        </tr>
        @endforeach
    </tbody>
</table>
<div class="footer">
    <div style="font-size:7pt;color:#888">
        <em>This document is confidential. For official use only.</em><br>
        Barangay New Era Management System
    </div>
    <div style="display:flex;gap:40px;align-items:flex-end">
        <div class="sig-line">
            <div style="height:28px"></div>
            <div class="line"></div>
            <div class="name">{{ $secretaryName }}</div>
            <div class="title">Barangay Secretary</div>
        </div>
        <div class="sig-line">
            <div style="height:28px"></div>
            <div class="line"></div>
            <div class="name">{{ $officialName }}</div>
            <div class="title">Punong Barangay</div>
        </div>
    </div>
</div>
</body>
</html>