<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
* { margin:0; padding:0; box-sizing:border-box; }
body { font-family: 'DejaVu Sans', sans-serif; font-size: 8pt; color: #111; }
.header { text-align:center; padding-bottom:10px; border-bottom:3px solid #0D2144; margin-bottom:12px; position:relative; }
.header .logo-left { position:absolute; left:0; top:0; width:55px; height:55px; }
.header .logo-right { position:absolute; right:0; top:0; width:55px; height:55px; }
.header .titles { padding:0 70px; }
.header .republic { font-size:8pt; font-style:italic; color:#444; }
.header .brgy { font-size:14pt; font-weight:bold; text-transform:uppercase; color:#0D2144; letter-spacing:0.05em; }
.header .office { font-size:8pt; color:#555; font-style:italic; }
.header .address { font-size:7.5pt; color:#777; }
.report-title { text-align:center; font-size:12pt; font-weight:bold; text-transform:uppercase; letter-spacing:0.1em; color:#0D2144; margin:10px 0 3px; text-decoration:underline; }
.report-sub { text-align:center; font-size:7.5pt; color:#666; margin-bottom:10px; }
.meta-bar { background:#f0f4f8; border:1px solid #dde2ea; padding:5px 10px; margin-bottom:10px; font-size:7.5pt; color:#444; }
table { width:100%; border-collapse:collapse; font-size:7.5pt; }
thead { display:table-header-group; }
thead tr th { background:#0D2144; color:#fff; padding:6px 8px; text-align:left; font-size:7pt; border:1px solid #0a1a36; }
tbody td { padding:5px 8px; border-bottom:1px solid #e5e7eb; vertical-align:top; }
.tr-odd  { background:#fff; }
.tr-even { background:#f5f7fa; }
tr.row-overdue td  { background:#fef2f2 !important; }
tr.row-expiring td { background:#fffbeb !important; }
.badge { display:inline-block; padding:1px 5px; border-radius:3px; font-size:6.5pt; font-weight:bold; margin:1px; }
.badge-green  { background:#dcfce7; color:#166534; }
.badge-red    { background:#fee2e2; color:#991b1b; }
.badge-yellow { background:#fef9c3; color:#854d0e; }
.badge-gray   { background:#f3f4f6; color:#6b7280; }
.badge-blue   { background:#dbeafe; color:#1e40af; }
.badge-orange { background:#ffedd5; color:#9a3412; }
.badge-gold   { background:#fef3dc; color:#92600a; }
.footer { margin-top:14px; padding-top:8px; border-top:2px solid #0D2144; display:flex; justify-content:space-between; align-items:center; font-size:7pt; color:#555; }
.sig-line { text-align:center; min-width:160px; }
.sig-line .line { border-top:1px solid #333; margin-bottom:3px; width:100%; }
.sig-line .name { font-weight:bold; font-size:7.5pt; text-transform:uppercase; }
.sig-line .title { font-size:7pt; color:#666; }
</style>
</head>
<body>
<div class="header">
    <img class="logo-left"  src="{{ public_path('images/qc-seal.png') }}" alt="QC">
    <img class="logo-right" src="{{ public_path('images/bne-logo.png') }}" alt="BNE">
    <div class="titles">
        <div class="republic"><em>Republic of the Philippines</em></div>
        <div style="font-size:8pt;color:#555">City of Quezon, National Capital Region</div>
        <div class="brgy">Barangay New Era</div>
        <div class="office">Office of the Punong Barangay</div>
        <div class="address">New Era, Quezon City, Metro Manila</div>
    </div>
</div>
<div class="report-title">Business Permits Report</div>
<div class="report-sub">
    As of {{ now()->format('m/d/Y') }}
    @if(!empty($filters['status'])) &nbsp;·&nbsp; Status: <strong>{{ $filters['status'] }}</strong> @endif
    @if(!empty($filters['business_type'])) &nbsp;·&nbsp; Type: <strong>{{ $filters['business_type'] }}</strong> @endif
    @if(!empty($filters['source'])) &nbsp;·&nbsp; Source: <strong>{{ ucfirst($filters['source']) }}</strong> @endif
    @if(!empty($filters['expiry_filter'])) &nbsp;·&nbsp; Expiry: <strong>{{ ucwords(str_replace('_', ' ', $filters['expiry_filter'])) }}</strong> @endif
</div>
@if(isset($activeFilters) && $activeFilters !== 'None (all records)')
<div style="background:#fef9c3;border:1px solid #fde68a;border-radius:3px;padding:4px 10px;margin-bottom:8px;font-size:7pt;color:#92400e;text-align:center">
    <strong>Filtered Export:</strong> {{ $activeFilters }}
</div>
@endif
<div class="meta-bar">
    <span>Total Records: <strong>{{ $data->count() }}</strong></span>
    <span>Generated by: <strong>{{ $generatedBy }}</strong> &nbsp;|&nbsp; {{ $generatedAt }}</span>
</div>
<table>
    <thead>
        <tr>
            <th style="width:25px">#</th>
            <th>Permit No.</th>
            <th>Business Name</th>
            <th>Type</th>
            <th>Owner</th>
            <th>Contact</th>
            <th>Address</th>
            <th>Permit Date</th>
            <th>Expiry</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach($data as $i => $b)
        @php
            $cls = match($b->status) { 'Active'=>'badge-green','Expired'=>'badge-red','Suspended'=>'badge-yellow',default=>'badge-gray' };
            $expiry = $b->expiry_date ? \Carbon\Carbon::parse($b->expiry_date) : null;
            $rowCls = '';
            if ($expiry && $b->status === 'Active') {
                if ($expiry->isPast())                  { $rowCls = 'row-overdue'; }
                elseif ($expiry->diffInDays(now()) <= 30) { $rowCls = 'row-expiring'; }
            }
        @endphp
        <tr class="{{ $rowCls ?: ($i % 2 === 0 ? 'tr-odd' : 'tr-even') }}">
            <td style="text-align:center;color:#888">{{ $i+1 }}</td>
            <td><strong>{{ $b->permit_number }}</strong></td>
            <td>{{ $b->business_name }}</td>
            <td>{{ $b->business_type }}</td>
            <td>{{ $b->owner_name }}</td>
            <td>{{ $b->owner_contact ?? '—' }}</td>
            <td>{{ $b->business_address }}</td>
            <td>{{ $b->permit_date ? \Carbon\Carbon::parse($b->permit_date)->format('m/d/Y') : '—' }}</td>
            <td>{{ $b->expiry_date ? \Carbon\Carbon::parse($b->expiry_date)->format('m/d/Y') : '—' }}</td>
            <td><span class="badge {{ $cls }}">{{ $b->status }}</span></td>
        </tr>
        @endforeach
    </tbody>
</table>
<div class="footer">
    <div style="font-size:7pt;color:#888">
        <em>This document is confidential. For official use only.</em><br>
        Barangay New Era Management System
    </div>
    <div style="display:flex;gap:40px;align-items:flex-end">
        <div class="sig-line">
            <div style="height:28px"></div>
            <div class="line"></div>
            <div class="name">{{ $secretaryName }}</div>
            <div class="title">Barangay Secretary</div>
        </div>
        <div class="sig-line">
            <div style="height:28px"></div>
            <div class="line"></div>
            <div class="name">{{ $officialName }}</div>
            <div class="title">Punong Barangay</div>
        </div>
    </div>
</div>
</body>
</html>