<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
* { margin:0; padding:0; box-sizing:border-box; }
body { font-family: 'DejaVu Sans', sans-serif; font-size: 8pt; color: #000; }
.header { display:flex; align-items:center; justify-content:space-between; padding-bottom:8px; border-bottom:2px solid #0D2144; margin-bottom:10px; }
.header img { width:48px; height:48px; }
.header-titles { text-align:center; flex:1; padding:0 10px; }
.header-titles .brgy { font-size:13pt; font-weight:bold; text-transform:uppercase; color:#0D2144; }
.header-titles .sub  { font-size:8pt; color:#444; }
.report-title { text-align:center; font-size:11pt; font-weight:bold; text-transform:uppercase; letter-spacing:0.1em; color:#0D2144; margin:8px 0 4px; text-decoration:underline; }
.meta { font-size:7.5pt; color:#555; margin-bottom:8px; display:flex; justify-content:space-between; }
table { width:100%; border-collapse:collapse; font-size:7.5pt; }
thead th { background:#0D2144; color:#fff; padding:5px 6px; text-align:left; font-size:7pt; text-transform:uppercase; letter-spacing:0.04em; }
tbody tr:nth-child(even) { background:#f5f7fa; }
tbody td { padding:4px 6px; border-bottom:1px solid #e5e7eb; vertical-align:top; }
.footer { margin-top:12px; padding-top:8px; border-top:1px solid #ccc; display:flex; justify-content:space-between; font-size:7pt; color:#666; }
.badge { display:inline-block; padding:1px 6px; border-radius:99px; font-size:6.5pt; font-weight:bold; }
.badge-green  { background:#dcfce7; color:#166534; }
.badge-red    { background:#fee2e2; color:#991b1b; }
.badge-yellow { background:#fef9c3; color:#854d0e; }
.badge-gray   { background:#f3f4f6; color:#6b7280; }
.badge-blue   { background:#dbeafe; color:#1e40af; }
.badge-orange { background:#ffedd5; color:#9a3412; }
</style>
</head>
<body>
<div class="header">
    <img src="{{ public_path('images/qc-seal.png') }}">
    <div class="header-titles">
        <div style="font-size:8pt;font-style:italic">Republic of the Philippines — City of Quezon, NCR</div>
        <div class="brgy">Barangay New Era</div>
        <div class="sub">Office of the Punong Barangay — New Era, Quezon City</div>
    </div>
    <img src="{{ public_path('images/bne-logo.png') }}">
</div>
<div class="report-title">Households Master List</div>
<div class="meta">
    <span>Total Records: <strong>{{ $data->count() }}</strong></span>
    <span>Generated by: <strong>{{ $generatedBy }}</strong> | {{ $generatedAt }}</span>
</div>
<table>
    <thead>
        <tr><th>#</th><th>Household No.</th><th>Household Head</th><th>Purok</th><th>Address</th><th>Family Size</th><th>Members</th><th>Voter HH</th><th>Registered</th></tr>
    </thead>
    <tbody>
        @foreach($data as $i => $h)
        <tr>
            <td>{{ $i+1 }}</td>
            <td><strong>{{ $h->household_number }}</strong></td>
            <td>{{ $h->household_head ?? '—' }}</td>
            <td>{{ $h->purok->name ?? '—' }}</td>
            <td>{{ $h->address }}</td>
            <td>{{ $h->family_size ?? '—' }}</td>
            <td>{{ $h->residents->count() }}</td>
            <td>{{ $h->is_voter_household ? 'Yes' : 'No' }}</td>
            <td>{{ $h->created_at->format('M d, Y') }}</td>
        </tr>
        @endforeach
    </tbody>
</table>
<div class="footer">
    <span>Barangay New Era Management System — Confidential</span>
    <span>Certified by: {{ $officialName }}, Punong Barangay</span>
</div>
</body></html>