<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
* { margin:0; padding:0; box-sizing:border-box; }
body { font-family: 'DejaVu Sans', sans-serif; font-size: 8pt; color: #111; }
.header { text-align:center; padding-bottom:10px; border-bottom:3px solid #0D2144; margin-bottom:12px; position:relative; }
.header .logo-left { position:absolute; left:0; top:0; width:55px; height:55px; }
.header .logo-right { position:absolute; right:0; top:0; width:55px; height:55px; }
.header .titles { padding:0 70px; }
.header .republic { font-size:8pt; font-style:italic; color:#444; }
.header .brgy { font-size:14pt; font-weight:bold; text-transform:uppercase; color:#0D2144; letter-spacing:0.05em; }
.header .office { font-size:8pt; color:#555; font-style:italic; }
.header .address { font-size:7.5pt; color:#777; }
.report-title { text-align:center; font-size:12pt; font-weight:bold; text-transform:uppercase; letter-spacing:0.1em; color:#0D2144; margin:10px 0 3px; text-decoration:underline; }
.report-sub { text-align:center; font-size:7.5pt; color:#666; margin-bottom:10px; }
.meta-bar { background:#f0f4f8; border:1px solid #dde2ea; padding:5px 10px; margin-bottom:10px; font-size:7.5pt; color:#444; }
table { width:100%; border-collapse:collapse; font-size:7.5pt; }
thead tr th { background:#0D2144; color:#fff; padding:6px 7px; text-align:left; font-size:7pt; border:1px solid #0a1a36; }
tbody td { padding:5px 7px; border-bottom:1px solid #e5e7eb; vertical-align:top; }
.tr-odd  { background:#fff; }
.tr-even { background:#f5f7fa; }
.badge { display:inline-block; padding:1px 5px; border-radius:3px; font-size:6.5pt; font-weight:bold; margin:1px; }
.badge-green  { background:#dcfce7; color:#166534; }
.badge-red    { background:#fee2e2; color:#991b1b; }
.badge-yellow { background:#fef9c3; color:#854d0e; }
.badge-gray   { background:#f3f4f6; color:#6b7280; }
.badge-blue   { background:#dbeafe; color:#1e40af; }
.badge-orange { background:#ffedd5; color:#9a3412; }
.badge-gold   { background:#fef3dc; color:#92600a; }
.footer { margin-top:14px; padding-top:8px; border-top:2px solid #0D2144; display:flex; justify-content:space-between; align-items:center; font-size:7pt; color:#555; }
.sig-line { text-align:center; min-width:160px; }
.sig-line .line { border-top:1px solid #333; margin-bottom:3px; width:100%; }
.sig-line .name { font-weight:bold; font-size:7.5pt; text-transform:uppercase; }
.sig-line .title { font-size:7pt; color:#666; }
</style>
</head>
<body>
<div class="header">
    <img class="logo-left"  src="{{ public_path('images/qc-seal.png') }}" alt="QC">
    <img class="logo-right" src="{{ public_path('images/bne-logo.png') }}" alt="BNE">
    <div class="titles">
        <div class="republic"><em>Republic of the Philippines</em></div>
        <div style="font-size:8pt;color:#555">City of Quezon, National Capital Region</div>
        <div class="brgy">Barangay New Era</div>
        <div class="office">Office of the Punong Barangay</div>
        <div class="address">New Era, Quezon City, Metro Manila</div>
    </div>
</div>
<div class="report-title">Households Master List</div>
<div class="report-sub">
    As of {{ now()->format('F d, Y') }}
    @if(!empty($filters['purok_id'])) &nbsp;·&nbsp; Purok ID: <strong>{{ $filters['purok_id'] }}</strong> @endif
    @if(!empty($filters['voter'])) &nbsp;·&nbsp; Voter HH: <strong>{{ ucfirst($filters['voter']) }}</strong> @endif
    @if(!empty($filters['s'])) &nbsp;·&nbsp; Search: <strong>{{ $filters['s'] }}</strong> @endif
</div>
@if(isset($activeFilters) && $activeFilters !== 'None (all records)')
<div style="background:#fef9c3;border:1px solid #fde68a;border-radius:3px;padding:4px 10px;margin-bottom:8px;font-size:7pt;color:#92400e;text-align:center">
    <strong>Filtered Export:</strong> {{ $activeFilters }}
</div>
@endif
<div class="meta-bar">
    <span>Total Records: <strong>{{ $data->count() }}</strong></span>
    <span>Generated by: <strong>{{ $generatedBy }}</strong> &nbsp;|&nbsp; {{ $generatedAt }}</span>
</div>
<table>
    <thead>
        <tr>
            <th style="width:25px">#</th>
            <th>Household No.</th>
            <th>Household Head</th>
            <th>Purok</th>
            <th>Address</th>
            <th>Family Size</th>
            <th>Members</th>
            <th>Voter HH</th>
            <th>Registered</th>
        </tr>
    </thead>
    <tbody>
        @foreach($data as $i => $h)
        <tr class="{{ $i % 2 === 0 ? 'tr-odd' : 'tr-even' }}">
            <td style="text-align:center;color:#888">{{ $i+1 }}</td>
            <td><strong>{{ $h->household_number }}</strong></td>
            <td>{{ $h->household_head ?? '—' }}</td>
            <td>{{ $h->purok->name ?? '—' }}</td>
            <td>{{ $h->address }}</td>
            <td style="text-align:center">{{ $h->family_size ?? '—' }}</td>
            <td style="text-align:center">{{ $h->residents->count() }}</td>
            <td><span class="badge {{ $h->is_voter_household ? 'badge-green' : 'badge-gray' }}">{{ $h->is_voter_household ? 'Yes' : 'No' }}</span></td>
            <td>{{ $h->created_at->format('m/d/Y') }}</td>
        </tr>
        @endforeach
    </tbody>
</table>
<div class="footer">
    <div style="font-size:7pt;color:#888">
        <em>This document is confidential. For official use only.</em><br>
        Barangay New Era Management System
    </div>
    <div style="display:flex;gap:40px;align-items:flex-end">
        <div class="sig-line">
            <div style="height:28px"></div>
            <div class="line"></div>
            <div class="name">{{ $secretaryName }}</div>
            <div class="title">Barangay Secretary</div>
        </div>
        <div class="sig-line">
            <div style="height:28px"></div>
            <div class="line"></div>
            <div class="name">{{ $officialName }}</div>
            <div class="title">Punong Barangay</div>
        </div>
    </div>
</div>
</body>
</html>