<?php

namespace App\Http\Controllers;

use App\Models\BlotterCase;
use App\Models\Business;
use App\Models\Document;
use App\Models\Household;
use App\Models\Purok;
use App\Models\Resident;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Http\Request;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

class ExportController extends Controller
{
    // -------------------------------------------------------
    // SHARED — Apply navy header style to a sheet
    // -------------------------------------------------------
    private function styleSheet($sheet, array $headers, array $colWidths): void
    {
        $colCount = count($headers);
        $lastCol = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($colCount);

        // Write headers
        foreach ($headers as $i => $h) {
            $col = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($i + 1);
            $sheet->setCellValue($col.'1', $h);
        }

        // Header row style — navy bg, white bold text
        $sheet->getStyle("A1:{$lastCol}1")->applyFromArray([
            'font' => [
                'bold' => true,
                'color' => ['argb' => 'FFFFFFFF'],
                'size' => 10,
            ],
            'fill' => [
                'fillType' => Fill::FILL_SOLID,
                'startColor' => ['argb' => 'FF0D2144'],
            ],
            'alignment' => [
                'horizontal' => Alignment::HORIZONTAL_CENTER,
                'vertical' => Alignment::VERTICAL_CENTER,
            ],
        ]);
        $sheet->getRowDimension(1)->setRowHeight(20);

        // Column widths
        foreach ($colWidths as $col => $width) {
            $sheet->getColumnDimension($col)->setWidth($width);
        }
    }

    private function styleDataRows($sheet, int $rowCount, int $colCount): void
    {
        $lastCol = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($colCount);

        for ($row = 2; $row <= $rowCount + 1; $row++) {
            // Alternating rows
            $bg = $row % 2 === 0 ? 'FFF5F7FA' : 'FFFFFFFF';
            $sheet->getStyle("A{$row}:{$lastCol}{$row}")->applyFromArray([
                'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => $bg]],
                'alignment' => ['vertical' => Alignment::VERTICAL_CENTER],
            ]);
            $sheet->getRowDimension($row)->setRowHeight(16);
        }

        // Border around all data
        $sheet->getStyle("A1:{$lastCol}".($rowCount + 1))->applyFromArray([
            'borders' => [
                'allBorders' => [
                    'borderStyle' => Border::BORDER_THIN,
                    'color' => ['argb' => 'FFE5E7EB'],
                ],
            ],
        ]);

        // Freeze header row
        $sheet->freezePane('A2');
    }

    private function addMetaSheet($spreadsheet, string $module, int $count, string $generatedBy, string $filtersApplied = 'None (all records)'): void
    {
        $meta = $spreadsheet->createSheet();
        $meta->setTitle('Info');
        $meta->setCellValue('A1', 'Barangay New Era BMS — Export Info');
        $meta->setCellValue('A2', 'Module');
        $meta->setCellValue('B2', ucfirst($module));
        $meta->setCellValue('A3', 'Total Records');
        $meta->setCellValue('B3', $count);
        $meta->setCellValue('A4', 'Filters Applied');
        $meta->setCellValue('B4', $filtersApplied);
        $meta->setCellValue('A5', 'Generated By');
        $meta->setCellValue('B5', $generatedBy);
        $meta->setCellValue('A6', 'Generated At');
        $meta->setCellValue('B6', now()->format('F d, Y h:i A'));
        $meta->setCellValue('A7', 'Barangay');
        $meta->setCellValue('B7', 'Barangay New Era, Quezon City');

        $meta->getStyle('A1')->applyFromArray([
            'font' => ['bold' => true, 'size' => 12, 'color' => ['argb' => 'FF0D2144']],
        ]);
        $meta->getStyle('A2:A7')->applyFromArray([
            'font' => ['bold' => true],
        ]);
        // Highlight filters row if filters are active
        if ($filtersApplied !== 'None (all records)') {
            $meta->getStyle('A4:B4')->applyFromArray([
                'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => 'FFFFF3CD']],
                'font' => ['color' => ['argb' => 'FF92400E']],
            ]);
        }
        $meta->getColumnDimension('A')->setWidth(20);
        $meta->getColumnDimension('B')->setWidth(50);
    }

    private function streamXlsx(Spreadsheet $spreadsheet, string $filename)
    {
        $writer = new Xlsx($spreadsheet);
        $response = response()->streamDownload(function () use ($writer) {
            $writer->save('php://output');
        }, $filename, [
            'Content-Type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'Cache-Control' => 'max-age=0',
        ]);

        return $response;
    }

    // -------------------------------------------------------
    // EXCEL EXPORTS
    // -------------------------------------------------------
    // Build a human-readable label from active filters for meta/header
    private function filterLabel(array $filters): string
    {
        $parts = [];
        $map = [
            'status'        => 'Status',
            'gender'        => 'Gender',
            'purok_id'      => 'Purok ID',
            'document_type' => 'Type',
            'incident_type' => 'Type',
            'business_type' => 'Business Type',
            'expiry_filter' => 'Expiry',
            'date_from'     => 'From',
            'date_to'       => 'To',
            'source'        => 'Source',
            'voter'         => 'Voter HH',
            's'             => 'Search',
        ];
        foreach ($map as $key => $label) {
            if (!empty($filters[$key])) {
                $parts[] = "{$label}: {$filters[$key]}";
            }
        }
        return $parts ? implode(' · ', $parts) : 'None (all records)';
    }

    public function excel(Request $request, string $module)
    {
        ini_set('memory_limit', '1024M');
        set_time_limit(120);

        $filters = $request->only([
            'status', 'gender', 'purok_id',
            'document_type', 'incident_type', 'business_type',
            'expiry_filter', 'date_from', 'date_to', 'source', 'voter', 's',
        ]);
        $date = now()->format('Y-m-d');
        $by = auth()->user()->name;

        switch ($module) {

            case 'residents':
                $data = Resident::with(['purok'])
                    ->when($filters['gender'] ?? null, fn ($q, $v) => $q->where('gender', $v))
                    ->when($filters['status'] ?? null, fn ($q, $v) => $q->where('residency_status', $v))
                    ->when($filters['purok_id'] ?? null, fn ($q, $v) => $q->where('purok_id', $v))
                    ->orderBy('last_name')->orderBy('first_name')->get();

                $ss = new Spreadsheet;
                $sheet = $ss->getActiveSheet()->setTitle('Residents');
                $headers = ['#', 'Last Name', 'First Name', 'Middle Name', 'Suffix', 'Gender', 'Birthdate', 'Age', 'Civil Status', 'Purok', 'Address', 'Contact', 'Email', 'Voter', 'Senior', 'PWD', 'Solo Parent', '4Ps', 'Status', 'Registered'];
                $widths = ['A' => 5, 'B' => 18, 'C' => 18, 'D' => 16, 'E' => 8, 'F' => 10, 'G' => 14, 'H' => 6, 'I' => 14, 'J' => 20, 'K' => 32, 'L' => 16, 'M' => 26, 'N' => 7, 'O' => 7, 'P' => 6, 'Q' => 12, 'R' => 6, 'S' => 14, 'T' => 14];
                $this->styleSheet($sheet, $headers, $widths);

                foreach ($data as $i => $r) {
                    $row = $i + 2;
                    $sheet->fromArray([$i + 1, $r->last_name, $r->first_name, $r->middle_name ?? '—', $r->suffix ?? '—', $r->gender, $r->birthdate?->format('M d, Y') ?? '—', $r->age ?? '—', $r->civil_status ?? '—', $r->purok->name ?? '—', $r->address, $r->contact_number ?? '—', $r->email_address ?? '—', $r->is_voter ? 'Yes' : 'No', $r->is_senior ? 'Yes' : 'No', $r->is_pwd ? 'Yes' : 'No', $r->is_solo_parent ? 'Yes' : 'No', $r->is_4ps ? 'Yes' : 'No', $r->residency_status, $r->created_at->format('M d, Y')], null, "A{$row}");
                }
                $this->styleDataRows($sheet, $data->count(), count($headers));
                $this->addMetaSheet($ss, 'Residents', $data->count(), $by, $this->filterLabel($filters));

                return $this->streamXlsx($ss, "residents-{$date}.xlsx");

            case 'households':
                $data = Household::with(['purok', 'residents'])
                    ->when($filters['purok_id'] ?? null, fn ($q, $v) => $q->where('purok_id', $v))
                    ->when(($filters['voter'] ?? null) === 'yes', fn ($q) => $q->where('is_voter_household', true))
                    ->when(($filters['voter'] ?? null) === 'no',  fn ($q) => $q->where('is_voter_household', false))
                    ->when($filters['s'] ?? null, fn ($q, $v) => $q->where(fn ($q2) => $q2
                        ->where('household_number', 'like', "%{$v}%")
                        ->orWhere('household_head', 'like', "%{$v}%")))
                    ->orderBy('household_number')->get();
                $ss = new Spreadsheet;
                $sheet = $ss->getActiveSheet()->setTitle('Households');
                $headers = ['#', 'Household No.', 'Household Head', 'Purok', 'Address', 'Family Size', 'Members', 'Voter HH', 'Registered'];
                $widths = ['A' => 5, 'B' => 16, 'C' => 22, 'D' => 20, 'E' => 35, 'F' => 12, 'G' => 10, 'H' => 12, 'I' => 14];
                $this->styleSheet($sheet, $headers, $widths);

                foreach ($data as $i => $h) {
                    $row = $i + 2;
                    $sheet->fromArray([$i + 1, $h->household_number, $h->household_head ?? '—', $h->purok->name ?? '—', $h->address, $h->family_size ?? '—', $h->residents->count(), $h->is_voter_household ? 'Yes' : 'No', $h->created_at->format('M d, Y')], null, "A{$row}");
                }
                $this->styleDataRows($sheet, $data->count(), count($headers));
                $this->addMetaSheet($ss, 'Households', $data->count(), $by, $this->filterLabel($filters));

                return $this->streamXlsx($ss, "households-{$date}.xlsx");

            case 'documents':
                $data = Document::with(['resident', 'issuedBy'])
                    ->when($filters['status'] ?? null, fn ($q, $v) => $q->where('status', $v))
                    ->when($filters['document_type'] ?? null, fn ($q, $v) => $q->where('document_type', $v))
                    ->when($filters['source'] ?? null, fn ($q, $v) => $q->where('source', $v))
                    ->orderBy('created_at', 'desc')->get();
                $ss = new Spreadsheet;
                $sheet = $ss->getActiveSheet()->setTitle('Documents');
                $headers = ['#', 'Doc Number', 'Document Type', 'Resident', 'Purpose', 'Status', 'Fee Paid', 'OR Number', 'Issued By', 'Date Requested', 'Date Released'];
                $widths = ['A' => 5, 'B' => 18, 'C' => 24, 'D' => 24, 'E' => 28, 'F' => 14, 'G' => 12, 'H' => 16, 'I' => 18, 'J' => 14, 'K' => 14];
                $this->styleSheet($sheet, $headers, $widths);

                foreach ($data as $i => $d) {
                    $row = $i + 2;
                    $sheet->fromArray([$i + 1, $d->doc_number, $d->document_type, $d->resident->full_name ?? '—', $d->purpose ?? '—', $d->status, $d->fee_paid > 0 ? '₱'.number_format($d->fee_paid, 2) : 'Free', $d->or_number ?? '—', $d->issuedBy->name ?? '—', $d->created_at->format('M d, Y'), $d->released_at?->format('M d, Y') ?? '—'], null, "A{$row}");
                }
                $this->styleDataRows($sheet, $data->count(), count($headers));
                $this->addMetaSheet($ss, 'Documents', $data->count(), $by, $this->filterLabel($filters));

                return $this->streamXlsx($ss, "documents-{$date}.xlsx");

            case 'blotter':
                $data = BlotterCase::with(['filedBy'])
                    ->when($filters['status'] ?? null, fn ($q, $v) => $q->where('status', $v))
                    ->when($filters['incident_type'] ?? null, fn ($q, $v) => $q->where('incident_type', $v))
                    ->when($filters['date_from'] ?? null, fn ($q, $v) => $q->whereDate('incident_date', '>=', $v))
                    ->when($filters['date_to'] ?? null, fn ($q, $v) => $q->whereDate('incident_date', '<=', $v))
                    ->when($filters['source'] ?? null, fn ($q, $v) => $q->where('source', $v))
                    ->orderBy('incident_date', 'desc')->get();
                $ss = new Spreadsheet;
                $sheet = $ss->getActiveSheet()->setTitle('Blotter Cases');
                $headers = ['#', 'Case Number', 'Incident Type', 'Incident Date', 'Location', 'Complainant', 'Respondent', 'Status', 'Filed By', 'Date Filed', 'Settled On'];
                $widths = ['A' => 5, 'B' => 18, 'C' => 20, 'D' => 14, 'E' => 28, 'F' => 22, 'G' => 22, 'H' => 24, 'I' => 18, 'J' => 14, 'K' => 14];
                $this->styleSheet($sheet, $headers, $widths);

                foreach ($data as $i => $b) {
                    $row = $i + 2;
                    $sheet->fromArray([$i + 1, $b->case_number, $b->incident_type, $b->incident_date ? \Carbon\Carbon::parse($b->incident_date)->format('M d, Y') : '—', $b->incident_location ?? '—', $b->complainant_name ?? '—', $b->respondent_name ?? '—', $b->status, $b->filedBy->name ?? '—', $b->created_at->format('M d, Y'), $b->settled_at?->format('M d, Y') ?? '—'], null, "A{$row}");
                }
                $this->styleDataRows($sheet, $data->count(), count($headers));
                $this->addMetaSheet($ss, 'Blotter', $data->count(), $by, $this->filterLabel($filters));

                return $this->streamXlsx($ss, "blotter-cases-{$date}.xlsx");

            case 'businesses':
                $data = Business::with(['issuedBy'])
                    ->when($filters['status'] ?? null, fn ($q, $v) => $q->where('status', $v))
                    ->when($filters['business_type'] ?? null, fn ($q, $v) => $q->where('business_type', $v))
                    ->when($filters['source'] ?? null, fn ($q, $v) => $q->where('source', $v))
                    ->when($filters['expiry_filter'] ?? null, function ($q, $v) {
                        if ($v === 'expired')       $q->where('expiry_date', '<', now())->where('status', 'Active');
                        elseif ($v === 'expiring_soon') $q->whereBetween('expiry_date', [now(), now()->addDays(30)])->where('status', 'Active');
                        elseif ($v === 'valid')     $q->where('expiry_date', '>', now()->addDays(30))->where('status', 'Active');
                    })
                    ->orderBy('business_name')->get();
                $ss = new Spreadsheet;
                $sheet = $ss->getActiveSheet()->setTitle('Business Permits');
                $headers = ['#', 'Permit No.', 'Business Name', 'Type', 'Owner', 'Contact', 'Address', 'Permit Date', 'Expiry Date', 'Status'];
                $widths = ['A' => 5, 'B' => 18, 'C' => 26, 'D' => 22, 'E' => 22, 'F' => 16, 'G' => 32, 'H' => 14, 'I' => 14, 'J' => 14];
                $this->styleSheet($sheet, $headers, $widths);

                foreach ($data as $i => $b) {
                    $row = $i + 2;
                    $sheet->fromArray([$i + 1, $b->permit_number, $b->business_name, $b->business_type, $b->owner_name, $b->owner_contact ?? '—', $b->business_address, $b->permit_date ? \Carbon\Carbon::parse($b->permit_date)->format('M d, Y') : '—', $b->expiry_date ? \Carbon\Carbon::parse($b->expiry_date)->format('M d, Y') : '—', $b->status], null, "A{$row}");
                }
                $this->styleDataRows($sheet, $data->count(), count($headers));
                $this->addMetaSheet($ss, 'Businesses', $data->count(), $by, $this->filterLabel($filters));

                return $this->streamXlsx($ss, "businesses-{$date}.xlsx");

            default:
                abort(404);
        }
    }

    // -------------------------------------------------------
    // PDF EXPORTS
    // -------------------------------------------------------
    public function pdf(Request $request, string $module)
    {
        // DomPDF is memory-intensive on large tables — raise limits before rendering
        ini_set('memory_limit', '2048M');
        set_time_limit(120);

        $filters = $request->only([
            'status', 'gender', 'purok_id',
            'document_type', 'incident_type', 'business_type',
            'expiry_filter', 'date_from', 'date_to', 'source', 'voter', 's',
        ]);
        $date         = now()->format('Y-m-d');
        $generatedAt  = now()->format('F d, Y \a\t h:i A');
        $generatedBy  = auth()->user()->name;
        $activeFilters = $this->filterLabel($filters);
        $officialName = \App\Models\Official::where('position', 'Punong Barangay')
            ->where('is_active', true)->first()?->full_name ?? 'ROBERT S. ROMANO';
        $secretaryName = \App\Models\Official::where('position', 'Barangay Secretary')
            ->where('is_active', true)->first()?->full_name ?? 'JOSEPHINE A. FLORES';

        switch ($module) {
            case 'residents':
                $data = Resident::with(['purok'])
                    ->when($filters['gender'] ?? null, fn ($q, $v) => $q->where('gender', $v))
                    ->when($filters['status'] ?? null, fn ($q, $v) => $q->where('residency_status', $v))
                    ->when($filters['purok_id'] ?? null, fn ($q, $v) => $q->where('purok_id', $v))
                    ->orderBy('last_name')->get();

                return Pdf::loadView('exports.pdf.residents', compact('data', 'generatedAt', 'generatedBy', 'officialName', 'secretaryName', 'filters', 'activeFilters'))
                    ->setPaper('a4', 'landscape')->stream("residents-{$date}.pdf");

            case 'households':
                $data = Household::with(['purok', 'residents'])
                    ->when($filters['purok_id'] ?? null, fn ($q, $v) => $q->where('purok_id', $v))
                    ->when(($filters['voter'] ?? null) === 'yes', fn ($q) => $q->where('is_voter_household', true))
                    ->when(($filters['voter'] ?? null) === 'no',  fn ($q) => $q->where('is_voter_household', false))
                    ->when($filters['s'] ?? null, fn ($q, $v) => $q->where(fn ($q2) => $q2
                        ->where('household_number', 'like', "%{$v}%")
                        ->orWhere('household_head', 'like', "%{$v}%")))
                    ->orderBy('household_number')->get();

                return Pdf::loadView('exports.pdf.households', compact('data', 'generatedAt', 'generatedBy', 'officialName', 'secretaryName', 'filters', 'activeFilters'))
                    ->setPaper('a4', 'landscape')->stream("households-{$date}.pdf");

            case 'documents':
                $data = Document::with(['resident', 'issuedBy'])
                    ->when($filters['status'] ?? null, fn ($q, $v) => $q->where('status', $v))
                    ->when($filters['document_type'] ?? null, fn ($q, $v) => $q->where('document_type', $v))
                    ->when($filters['source'] ?? null, fn ($q, $v) => $q->where('source', $v))
                    ->orderBy('created_at', 'desc')->get();

                return Pdf::loadView('exports.pdf.documents', compact('data', 'generatedAt', 'generatedBy', 'officialName', 'secretaryName', 'filters', 'activeFilters'))
                    ->setPaper('a4', 'landscape')->stream("documents-{$date}.pdf");

            case 'blotter':
                $data = BlotterCase::with(['filedBy'])
                    ->when($filters['status'] ?? null, fn ($q, $v) => $q->where('status', $v))
                    ->when($filters['incident_type'] ?? null, fn ($q, $v) => $q->where('incident_type', $v))
                    ->when($filters['date_from'] ?? null, fn ($q, $v) => $q->whereDate('incident_date', '>=', $v))
                    ->when($filters['date_to'] ?? null, fn ($q, $v) => $q->whereDate('incident_date', '<=', $v))
                    ->when($filters['source'] ?? null, fn ($q, $v) => $q->where('source', $v))
                    ->orderBy('incident_date', 'desc')->get();

                return Pdf::loadView('exports.pdf.blotter', compact('data', 'generatedAt', 'generatedBy', 'officialName', 'secretaryName', 'filters', 'activeFilters'))
                    ->setPaper('a4', 'landscape')->stream("blotter-cases-{$date}.pdf");

            case 'businesses':
                $data = Business::with(['issuedBy'])
                    ->when($filters['status'] ?? null, fn ($q, $v) => $q->where('status', $v))
                    ->when($filters['business_type'] ?? null, fn ($q, $v) => $q->where('business_type', $v))
                    ->when($filters['source'] ?? null, fn ($q, $v) => $q->where('source', $v))
                    ->when($filters['expiry_filter'] ?? null, function ($q, $v) {
                        if ($v === 'expired')           $q->where('expiry_date', '<', now())->where('status', 'Active');
                        elseif ($v === 'expiring_soon') $q->whereBetween('expiry_date', [now(), now()->addDays(30)])->where('status', 'Active');
                        elseif ($v === 'valid')         $q->where('expiry_date', '>', now()->addDays(30))->where('status', 'Active');
                    })
                    ->orderBy('business_name')->get();

                return Pdf::loadView('exports.pdf.businesses', compact('data', 'generatedAt', 'generatedBy', 'officialName', 'secretaryName', 'filters', 'activeFilters'))
                    ->setPaper('a4', 'landscape')->stream("businesses-{$date}.pdf");

            case 'committees':
                $slug      = $request->input('slug', '');
                $slugMap   = [
                    'peace-order'    => 'Peace & Order',
                    'health'         => 'Health',
                    'education'      => 'Education',
                    'infrastructure' => 'Infrastructure',
                    'environment'    => 'Environment',
                    'livelihood'     => 'Livelihood',
                    'transport'      => 'Transport & Comm.',
                    'bdrrm'          => 'BDRRM',
                ];
                $committeeName = $slugMap[$slug] ?? 'Committee';

                $records       = \App\Models\CommitteeRecord::where('committee_slug', $slug)->latest()->get();
                $activities    = \App\Models\CommitteeActivity::where('committee_slug', $slug)->latest()->get();
                $attendances   = \App\Models\CommitteeAttendance::where('committee_slug', $slug)->latest()->get();
                $inventory     = \App\Models\CommitteeInventory::where('committee_slug', $slug)->latest()->get();
                $partnerships  = \App\Models\CommitteePartnership::where('committee_slug', $slug)->latest()->get();

                return Pdf::loadView('exports.pdf.committee', compact(
                    'slug', 'committeeName', 'records', 'activities', 'attendances', 'inventory', 'partnerships',
                    'generatedAt', 'generatedBy', 'officialName', 'secretaryName'
                ))->setPaper('a4', 'portrait')->stream("{$slug}-report-{$date}.pdf");

            default:
                abort(404);
        }
    }

    // -------------------------------------------------------
    // ANALYTICS EXPORT
    // -------------------------------------------------------
    public function analytics(Request $request, string $format)
    {
        $date = now()->format('Y-m-d');
        $generatedAt = now()->format('F d, Y \a\t h:i A');
        $generatedBy = auth()->user()->name;
        $officialName = \App\Models\Official::where('position', 'Punong Barangay')
            ->where('is_active', true)->first()?->full_name ?? 'ROBERT S. ROMANO';
        $secretaryName = \App\Models\Official::where('position', 'Barangay Secretary')
            ->where('is_active', true)->first()?->full_name ?? 'JOSEPHINE A. FLORES';

        // Gather all analytics data
        $totalResidents = Resident::count();
        $totalActive = Resident::where('residency_status', 'Active')->count();
        $totalDeceased = Resident::where('residency_status', 'Deceased')->count();
        $totalTransferred = Resident::where('residency_status', 'Transferred')->count();
        $totalMale = Resident::where('gender', 'Male')->count();
        $totalFemale = Resident::where('gender', 'Female')->count();
        $totalHouseholds = Household::count();
        $totalVoters = Resident::where('is_voter', true)->count();
        $totalSeniors = Resident::where('is_senior', true)->count();
        $totalPwd = Resident::where('is_pwd', true)->count();
        $totalSoloParent = Resident::where('is_solo_parent', true)->count();
        $total4ps = Resident::where('is_4ps', true)->count();

        $ageGroups = [
            'Children (0-12)' => Resident::whereBetween(\DB::raw('TIMESTAMPDIFF(YEAR, birthdate, CURDATE())'), [0, 12])->count(),
            'Teens (13-17)' => Resident::whereBetween(\DB::raw('TIMESTAMPDIFF(YEAR, birthdate, CURDATE())'), [13, 17])->count(),
            'Adults (18-59)' => Resident::whereBetween(\DB::raw('TIMESTAMPDIFF(YEAR, birthdate, CURDATE())'), [18, 59])->count(),
            'Seniors (60+)' => Resident::where(\DB::raw('TIMESTAMPDIFF(YEAR, birthdate, CURDATE())'), '>=', 60)->count(),
        ];

        $residentsByPurok = Purok::withCount(['residents' => fn ($q) => $q->where('residency_status', 'Active')])
            ->orderBy('name')->get();

        if ($format === 'pdf') {
            return Pdf::loadView('exports.pdf.analytics', compact(
                'generatedAt', 'generatedBy', 'officialName', 'secretaryName',
                'totalResidents', 'totalActive', 'totalDeceased', 'totalTransferred',
                'totalMale', 'totalFemale', 'totalHouseholds',
                'totalVoters', 'totalSeniors', 'totalPwd', 'totalSoloParent', 'total4ps',
                'ageGroups', 'residentsByPurok'
            ))->setPaper('a4', 'portrait')->stream("population-summary-{$date}.pdf");
        }

        // Excel
        $ss = new Spreadsheet;
        $sheet = $ss->getActiveSheet()->setTitle('Population Summary');

        // Title row
        $sheet->setCellValue('A1', 'BARANGAY NEW ERA — POPULATION SUMMARY REPORT');
        $sheet->setCellValue('A2', 'As of '.now()->format('F d, Y'));
        $sheet->setCellValue('A3', 'Generated by: '.$generatedBy.' | '.$generatedAt);
        $sheet->getStyle('A1')->applyFromArray(['font' => ['bold' => true, 'size' => 14, 'color' => ['argb' => 'FF0D2144']]]);
        $sheet->getStyle('A2:A3')->applyFromArray(['font' => ['size' => 9, 'color' => ['argb' => 'FF666666']]]);

        // Overall Population
        $sheet->setCellValue('A5', 'OVERALL POPULATION');
        $sheet->getStyle('A5')->applyFromArray(['font' => ['bold' => true, 'color' => ['argb' => 'FFFFFFFF']], 'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => 'FF0D2144']]]);
        $sheet->mergeCells('A5:B5');

        $popData = [['Total Residents', $totalResidents], ['Active', $totalActive], ['Deceased', $totalDeceased], ['Transferred', $totalTransferred], ['Total Households', $totalHouseholds]];
        $row = 6;
        foreach ($popData as $i => $d) {
            $sheet->setCellValue("A{$row}", $d[0]);
            $sheet->setCellValue("B{$row}", $d[1]);
            $bg = $row % 2 === 0 ? 'FFF5F7FA' : 'FFFFFFFF';
            $sheet->getStyle("A{$row}:B{$row}")->applyFromArray(['fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => $bg]]]);
            $row++;
        }

        // Gender
        $row++;
        $sheet->setCellValue("A{$row}", 'GENDER DISTRIBUTION');
        $sheet->getStyle("A{$row}")->applyFromArray(['font' => ['bold' => true, 'color' => ['argb' => 'FFFFFFFF']], 'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => 'FF0D2144']]]);
        $sheet->mergeCells("A{$row}:C{$row}");
        $row++;
        $sheet->fromArray(['Gender', 'Count', '%'], null, "A{$row}");
        $sheet->getStyle("A{$row}:C{$row}")->applyFromArray(['font' => ['bold' => true], 'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => 'FFE8EDF5']]]);
        $row++;
        $total = $totalMale + $totalFemale;
        $sheet->fromArray(['Male', $totalMale, $total > 0 ? round(($totalMale / $total) * 100).'%' : '0%'], null, "A{$row}");
        $row++;
        $sheet->fromArray(['Female', $totalFemale, $total > 0 ? round(($totalFemale / $total) * 100).'%' : '0%'], null, "A{$row}");
        $row++;

        // Age Groups
        $row++;
        $sheet->setCellValue("A{$row}", 'AGE GROUPS');
        $sheet->getStyle("A{$row}")->applyFromArray(['font' => ['bold' => true, 'color' => ['argb' => 'FFFFFFFF']], 'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => 'FF0D2144']]]);
        $sheet->mergeCells("A{$row}:C{$row}");
        $row++;
        $sheet->fromArray(['Age Group', 'Count', '%'], null, "A{$row}");
        $sheet->getStyle("A{$row}:C{$row}")->applyFromArray(['font' => ['bold' => true], 'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => 'FFE8EDF5']]]);
        $row++;
        foreach ($ageGroups as $label => $count) {
            $pct = $totalActive > 0 ? round(($count / $totalActive) * 100).'%' : '0%';
            $sheet->fromArray([$label, $count, $pct], null, "A{$row}");
            $row++;
        }

        // Special Classifications
        $row++;
        $sheet->setCellValue("A{$row}", 'SPECIAL CLASSIFICATIONS');
        $sheet->getStyle("A{$row}")->applyFromArray(['font' => ['bold' => true, 'color' => ['argb' => 'FFFFFFFF']], 'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => 'FF0D2144']]]);
        $sheet->mergeCells("A{$row}:C{$row}");
        $row++;
        $sheet->fromArray(['Classification', 'Count', '% of Active'], null, "A{$row}");
        $sheet->getStyle("A{$row}:C{$row}")->applyFromArray(['font' => ['bold' => true], 'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => 'FFE8EDF5']]]);
        $row++;
        $classifications = [['Registered Voters', $totalVoters], ['Senior Citizens', $totalSeniors], ['PWD', $totalPwd], ['Solo Parents', $totalSoloParent], ['4Ps Beneficiaries', $total4ps]];
        foreach ($classifications as $c) {
            $pct = $totalActive > 0 ? round(($c[1] / $totalActive) * 100).'%' : '0%';
            $sheet->fromArray([$c[0], $c[1], $pct], null, "A{$row}");
            $row++;
        }

        // Residents by Purok
        $row++;
        $sheet->setCellValue("A{$row}", 'RESIDENTS BY PUROK');
        $sheet->getStyle("A{$row}")->applyFromArray(['font' => ['bold' => true, 'color' => ['argb' => 'FFFFFFFF']], 'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => 'FF0D2144']]]);
        $sheet->mergeCells("A{$row}:C{$row}");
        $row++;
        $sheet->fromArray(['Purok', 'Residents', '% of Total'], null, "A{$row}");
        $sheet->getStyle("A{$row}:C{$row}")->applyFromArray(['font' => ['bold' => true], 'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => 'FFE8EDF5']]]);
        $row++;
        foreach ($residentsByPurok as $purok) {
            $pct = $totalActive > 0 ? round(($purok->residents_count / $totalActive) * 100).'%' : '0%';
            $sheet->fromArray([$purok->name, $purok->residents_count, $pct], null, "A{$row}");
            $row++;
        }

        // Column widths
        $sheet->getColumnDimension('A')->setWidth(30);
        $sheet->getColumnDimension('B')->setWidth(15);
        $sheet->getColumnDimension('C')->setWidth(15);

        $this->addMetaSheet($ss, 'Analytics', $totalResidents, $generatedBy);

        return $this->streamXlsx($ss, "population-summary-{$date}.xlsx");
    }
}
